using Newtonsoft.Json;

namespace FacturacionElectronica.Net.Xml.Model.Account
{
    public class Login
    {
        /// <summary>
        /// Código del usuario (Login) en la aplicación
        /// User Login
        /// </summary>
        public required string UserId { get; set; }

        /// <summary>
        /// Contraseña
        /// Password 
        /// </summary>
        public required string Password { get; set; }

        /// <summary>
        /// Indica si se debe generar o no un token de actualizacion (RefreshToken)
        /// Indicates whether or not a refresh token should be generated (RefreshToken) 
        /// </summary>
        public bool RememberMe { get; set; }

        /// <summary>
        /// Id de la empresa en la base de datos o Código de la empresa en el ERP. Nota: En caso de no contar con este valor enviar “0”
        /// Company ID in the database or Company Code in the ERP. Note: If you do not have this value, send "0" 
        /// </summary>        
        public required string EmpresaId { get; set; }

        /// <summary>
        /// Nombre de la aplicación desde la que se esta solicitando el inicio de sesión, para su identificación en la base de datos
        /// Name of the application from which the login is being requested, for identification in the database 
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]       
        public string? AplicacionId { get; set; }

        /// <summary>
        /// Version del navegador de internet. O version del sistema operativo en apps mobiles donde se esta ejecutando la aplicación
        /// Internet browser version. Or version of the operating system in mobile apps where the application is running
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]       
        public string? BrowserSOVersion { get; set; }

        /// <summary>
        /// Código del Token (Token Id) del dispositivo para enviar notificaciones push por Firebase a los clientes web o móviles
        /// Token Id of the device to send push notifications by Firebase to web or mobile clients
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]       
        public string? DispositivoId { get; set; }

        /// <summary>
        /// Token generado por servicio de Google reCaptcha
        /// Token generated by Google reCaptcha service
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]        
        public string? ReCaptchaToken { get; set; }

        /// <summary>
        /// Dirección IP del dispositivo desde el cual se esta consumiendo la API
        /// IP address of the device from which the API is being consumed 
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]        
        public string? ClientIPAddress { get; set; }
    }
}
